#sdk: "/Users/Ryota/.rvm/gems/ruby-1.9.3-p194@rhodes/gems/rhodes-3.3.3"
sdkversion: 3.3.3
name: contact
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.contact
  BundleURLScheme: contact
wp:
  productid: '04f88f40-bc4d-012f-250d-3c07542aa8a3'
symbian:
  uid: '0xe131bd2b'
android:
  version: 2.1
capabilities:
- pim
extensions: ["json", "another-extension"]
